#!/bin/sh -e

echo "-> Copying sources ..."
cp -Rf /tmp/src/. ./

# Check if hugo can compile your site
hugo --baseURL=${HUGO_BASE_URL:-http://hugo2-spurtell-hugo.e8ca.engint.openshiftapps.com} --theme ${HUGO_THEME:-mainroad} \
     --renderToMemory -v && rm -rf public
